### ISSUE TITLE
Add JMX Enhancer to the list

### ISSUE THREAD

**Issue by Ajay-056** [QAInsights/Performance-Engineers-Utilities#1]
Hi Naveen,

I recently came across this utility called JMX Enhancer they are providing 5 solutions for scripting and other stuffs in JMeter which could help save the script effort to some extent. 

Here is the link for the same    https://jmxenhancer.com/index.html

They have the browser extension also just we have to sign up for pro user using business email for which we can use 10minutesmail to use their service

![image](https://user-images.githubusercontent.com/40629789/138596529-c8e5e487-ef00-44a3-a7a5-2c30ca60a9fe.png)

**Comment by QAInsights** [comment]
@Ajay-056 I am not adding the above tool as it has not been updated for the past 2 years. Instead, please check Blazemeter Auto Correlation plugin. Thanks!
